//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ucak_web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ucakEntities3 : DbContext
    {
        public ucakEntities3()
            : base("name=ucakEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<firmalar> firmalar { get; set; }
        public virtual DbSet<kullanicilar> kullanicilar { get; set; }
        public virtual DbSet<yolcular> yolcular { get; set; }
    }
}
