//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ucak_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class yolcular
    {
        public int ID { get; set; }
        public string yolcu_ad { get; set; }
        public string yolcu_soyad { get; set; }
        public string yolcu_cinsiyet { get; set; }
        public int yolcu_dogumyili { get; set; }
        public string nereden { get; set; }
        public string nereye { get; set; }
        public int firma_kodu { get; set; }
        public int yolcu_koltukno { get; set; }
        public Nullable<System.DateTime> yolcu_kayit_tarihi { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public string fotograf { get; set; }
    
        public virtual firmalar firmalar { get; set; }
    }
}
